package main

import "net/http"

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},
	Route{
		"UserAuthenticate",
		"POST",
		"/login",
		UserAuthenticate,
	},
	Route{
		"UserCreate",
		"POST",
		"/users",
		UserCreate,
	},
	Route{
		"PatientCreate",
		"POST",
		"/patients",
		PatientCreate,
	},
	Route{
		"PatientGet",
		"GET",
		"/patients/patientuuid/{patientuuid}",
		PatientGet,
	},
	Route{
		"PatientGetByDoctor",
		"GET",
		"/patients/doctoruuid/{doctoruuid}",
		PatientGetByDoctor,
	},
	Route{
		"FutureAppointmentCreate",
		"POST",
		"/futureappointments",
		FutureAppointmentCreate,
	},
	Route{
		"FutureAppointmentGet",
		"GET",
		"/futureappointments/search",
		FutureAppointmentGet,
	},
	Route{
		"CompletedAppointmentCreate",
		"POST",
		"/completedappointments",
		CompletedAppointmentCreate,
	},
	Route{
		"CompletedAppointmentGet",
		"GET",
		"/completedappointments/appointmentuuid/{apointmentuuid}",
		CompletedAppointmentGet,
	},
	Route{
		"AppointmentGetByDoctor",
		"GET",
		"/appointments/doctoruuid/{doctoruuid}",
		AppointmentGetByDoctor,
	},
	Route{
		"DoctorCreate",
		"POST",
		"/doctors",
		DoctorCreate,
	},
	Route{
		"DoctorGet",
		"GET",
		"/doctors/doctoruuid/{doctoruuid}",
		DoctorGet,
	},
	Route{
		"PrescriptionCreate",
		"POST",
		"/prescription",
		PrescriptionCreate,
	},
	Route{
		"PrescriptionsGetByPatient",
		"GET",
		"/prescriptions/patientuuid/{patientuuid}",
		PrescriptionsGetByPatient,
	},
	Route{
		"AppointmentGetByPatient",
		"GET",
		"/appointments/patientuuid/{patientuuid}",
		AppointmentGetByPatient,
	},
	Route{
		"PatientUpdate",
		"PUT",
		"/patients",
		PatientUpdate,
	},
	Route{
		"NotificationCreate",
		"POST",
		"/notifications",
		NotificationCreate,
	},
	Route{
		"NotificationsGetByDoctor",
		"GET",
		"/notifications/doctoruuid/{doctoruuid}",
		NotificationsGetByDoctor,
	Route{
		"DocumentUpload",
		"POST",
		"/documents",
		DocumentUpload,
	},
	Route{
		"DocumentGet",
		"GET",
		"/documents/documentuuid/{documentuuid}",
		DocumentGet,
	},
}
